### ISSUE TITLE
Collect draft SOPs

### ISSUE THREAD

**Issue by lonelyjoeparker** [realtimephylogenomics/lab-strain-resequencing-pipeline#2]
As the lab manager, 
I want to see the draft SOPs
So I can work out how complete they are at the moment

**Comment by lonelyjoeparker** [comment]
we will also want a labelling system
and a sample check sheet / tracking sheet

**Comment by lonelyjoeparker** [comment]
@conorg150 made a start on thjis e.g https://sotonac.sharepoint.com/:x:/r/teams/Webbgroup/_layouts/15/Doc.aspx?sourcedoc=%7B08F89516-105E-48EB-883F-B8CD4B48A4CB%7D&file=Sequencing_Project_Sample_Repository.xlsx&action=default&mobileredirect=true

@KirstyCooper

**Comment by conorg150** [comment]
draft SOP's have been uploaded to Webb group teams site
https://sotonac.sharepoint.com/:w:/r/teams/Webbgroup/Shared%20Documents/Webb_group_resequencing_project_2022/Protocols.docx?d=w98bd230ae8824df68c550f6132aa7aa9&csf=1&web=1&e=oP85uF
