### ISSUE TITLE
Procure lab consumables

### ISSUE THREAD

**Issue by lonelyjoeparker** [realtimephylogenomics/lab-strain-resequencing-pipeline#3]
As the lab team
I want to procure all the kits and reagents for sequencing
so that we can work in the lab

**Comment by lonelyjoeparker** [comment]
@conorg150 moved this to in progress as it's on the workplan to happen this week and is blocking other issues.

**Comment by conorg150** [comment]
@lonelyjoeparker these are the laser printer barcode labels i was talking about https://www.fishersci.co.uk/shop/products/fisherbrand-micryo-dots-strips-cryo-storage-laser-printer-sheets-11/16468115

**Comment by lonelyjoeparker** [comment]
(re: barcodes)
Kirsty: it would be a good idea to have the ability to label effectively, 
Conor: it's about £30
Joe: Feels like feature creep but fair dos

**Comment by lonelyjoeparker** [comment]
Conor's got the order forms, just checking the lead times.

**Comment by conorg150** [comment]
All orders placed with bsorder using the code provided in the 'cost centre code' issue. Email sent to Jeremy to remind him to check for new orders awaiting approval.
Asked bsorder to place the oxford nanopore order directly if possible (I think Mark Dixon has his own account), however we will place the order directly through the store using the PO number provided if that is not possible

**Comment by lonelyjoeparker** [comment]
Order placed now @conorg150 
was 10.4 / Chemistry 12 / Q20+ *not* 10.4.1 / Chemistry 14.. right?
