### ISSUE TITLE
Validate bioinformatics

### ISSUE THREAD

**Issue by lonelyjoeparker** [realtimephylogenomics/lab-strain-resequencing-pipeline#34]
As a user (bioinformatician)
I want to know the pipeline from @conorg150 works
So I can use it

**Comment by lonelyjoeparker** [comment]
Have started to populate an architecture diagram for this at https://miro.com/app/board/uXjVOkAgg0s=/

@conorg150 pls can you do these two things - (1) identify a suitable example dataset so I can e2e (end-to-end) test on my Iridis, and (2) finish off the diagram yourself - or I can do it with you if you like? I've made a start

**Comment by conorg150** [comment]
I've left the example dataset with scripts and strain/barcode/best_contig.txt at '/research/NBICgenomics/pipeline_test_data'. This is a full minION run of Declan's data using the exact same reagents and protocol we will be using. It is very large, and so the basecalling will likely take around 10 hours. If you want it to run faster, trim down the dataset as opposed to changing the guppy parameters as this may break the assembly step. There is also the manual.txt which should hopefully cover everything that you need (let me know if it doesn't). 

I've also had a go at updating the architecture diagram, let me know if it's any good.

**Comment by conorg150** [comment]
Have also put the kraken2 database in there @lonelyjoeparker
