### ISSUE TITLE
the notification email address in the basecalling and other scripts needs to be notifiable

### ISSUE THREAD

**Issue by lonelyjoeparker** [realtimephylogenomics/lab-strain-resequencing-pipeline#37]
At the moment the email address for notifications from the HPC cluster to the user is hardcoded in `Seq_pipeline_basecalling.sh`:

https://github.com/realtimephylogenomics/lab-strain-resequencing-pipeline/blob/48def05e661915d2c6ce821e3adf141906a6e8e0/Seq_pipeline_basecalling.sh#L7

Instead this should be passed to the script as a parameter.

**Comment by lonelyjoeparker** [comment]
Should check the equivalent behaviour is applied to the other two scripts as well @conorg150

**Comment by conorg150** [comment]
There is actually no way of passing this to slurm as a variable/parameter from within a script. You can specify an email at the command line, however this will only work for the basecalling script, as the computation script is not run from the CLI. 

There are other ways of sending emails from within linux, however they usually require the installation of programs that would complicate installation. The least complicated way for users and coders (IMO) is just to edit the header at the top of the bash script

**Comment by lonelyjoeparker** [comment]
Ah right, forgot this was passed as a comment line not evaluated at runtime. There is a kludge at https://stackoverflow.com/questions/14712863/variable-expansion-in-comments but agree it looks nasty.
