### ISSUE TITLE
Organise logistics - lab space

### ISSUE THREAD

**Issue by lonelyjoeparker** [realtimephylogenomics/lab-strain-resequencing-pipeline#5]
As the lab manager
I want to know we have enough bench space for the projecyt
And which space (and when) 
So that we aren't space-limited

**Comment by KirstyCooper** [comment]
Franklin has spoken to me about the instrument room suggesting that we leave it and do it on the outside Cat1 benches instead. He thinks the changes that need making are school problems and its going to take months so will not be ready in time. We are welcome to go through and do it ourselves but thinks it will be a lot of work for us.

**Comment by lonelyjoeparker** [comment]
OK cool. Cheers @KirstyCooper . Hopefully you've seen the email from him yesterday evening

**Comment by KirstyCooper** [comment]
I have and to put in writing here, Franklin has updated us with new developments in the school meaning the sequencing room is ready for us to use
