### ISSUE TITLE
Organise logistics - wider stakeholders

### ISSUE THREAD

**Issue by lonelyjoeparker** [realtimephylogenomics/lab-strain-resequencing-pipeline#6]
As a stakeholder (lab user more generally, including visitors)
I want to know what's happening in the lab for this project
So that I don't get pissed off when its busy

**Comment by KirstyCooper** [comment]
25/08 - Bill, Franklin, and Sandra have been informed about the project and warned of the 2 planned weeks. Other lab users will be told mid-late September.

**Comment by lonelyjoeparker** [comment]
It seems like we need a better DoD for this issue eg 'at what point are we happy that we've been good lab citizens and diligently informed colleagues / at what point do we stop trying and just crack on'
